import tundayImg from "../../assets/restaurant1.jpg";
import tundayLogo from "../../assets/syam.png";

import shyamBakeryImg from "../../assets/restaurant1.jpg";
import shyamBakeryLogo from "../../assets/syam.png";

import idreesImg from "../../assets/restaurant3.jpg";
import idreesLogo from "../../assets/restaurant3.jpg";

import dastarkhwanImg from "../../assets/restaurant4.jpg";
import dastarkhwanLogo from "../../assets/restaurant4.jpg";

import royalCafeImg from "../../assets/restaurant5.jpg";
import royalCafeLogo from "../../assets/restaurant5.jpg";

import marksmenImg from "../../assets/restaurant3.jpg";
import marksmenLogo from "../../assets/restaurant3.jpg";

import rahimImg from "../../assets/restaurant4.jpg";
import rahimLogo from "../../assets/restaurant4.jpg";

import mubeensImg from "../../assets/restaurant5.jpg";
import mubeensLogo from "../../assets/restaurant5.jpg";

import kalikaImg from "../../assets/restaurant3.jpg";
import kalikaLogo from "../../assets/restaurant3.jpg";
import slide1 from "../../assets/bnanner (1).png";
import slides from "../../assets/bnanner (1).png";
import slides2 from "../../assets/bnanner (1).png";

const Featured = [

  {
    id: 1,
    title: "Shyam Namkeen & Bakers",
    subtitle: "Shyam Namkeen & Bakers",
    address: " Dandahia Chauk, Aliganj, Lucknow, Uttar Pradesh 226021",
    phone: "+91 97930 00002",
    category: "Namkeen & Bakery",
    image: shyamBakeryImg,
    logo: shyamBakeryLogo,
    slides: [slide1, slides2, slides],
    categories: [
      { name: "Namkeen", id: "namkeen" },
      { name: "Chips", id: "chips" },
      { name: "Sev", id: "sev" },
      { name: "Bhujiya", id: "bhujiya" },
      { name: "Kaju Namkeen", id: "kajunamkeen" },
      { name: "Single Items", id: "singleitems" },
      { name: "Chura", id: "chura" },
      { name: "Biscuits", id: "biscuits" },
      { name: "Breads", id: "breads" },
      { name: "Rusk", id: "rusk" },
      { name: "Festive Specials", id: "festive-specials" },
      { name: "Combo Packs", id: "combo-packs" },
      { name: "New Arrivals", id: "new-arrivals" }
    ],
    categoryLink: "bakery",
    cardLink: "ShyamBakery",
    status: "Open",
    rating: 4.4,
    desc: "Shyam Namkeen & Bakers is known for its delightful baked creations and unforgettable taste experience. We offer freshly baked breads, cakes, pastries, and savory treats prepared daily using premium-quality ingredients and time-honored recipes. Every product is crafted with care to ensure perfect texture, rich flavor, and consistent quality. From classic favorites to modern specialties, Shyam Bakery brings warmth, sweetness, and freshness to every bite — making it the perfect place for celebrations, casual cravings, and everyday indulgence.",
    gst: 9043898996702,
    fssai: 789973249789798,
    totalRatings: 185,
    followers: 3200,
    products: 150,
    showAdd: true,
  },

  {
    id: 2,
    title: "Restaurant",
    subtitle: "Lucknowi Dum Biryani",
    address: "Chowk, Lucknow",
    phone: "+91 97930 00002",
    category: "Biryani Restaurant",
    image: idreesImg,
    logo: idreesLogo,
    slides: [idreesImg, idreesImg, idreesImg],
    categories: [
      { name: "Biryani", id: "biryani" },
      { name: "Chicken Dishes", id: "chicken-dishes" },
      { name: "Mutton Dishes", id: "mutton-dishes" },
      { name: "Kebabs", id: "kebabs" },
      { name: "Gravy Items", id: "gravy-items" },
      { name: "Tandoor Special", id: "tandoor-special" },
      { name: "Roti & Rice", id: "roti-rice" },
      { name: "Desserts", id: "desserts" },
      { name: "Beverages", id: "beverages" }
    ],
    categoryLink: "restaurant",
    cardLink: "biryanirestaurant",
    status: "Open",
    rating: 4.8,
    desc: "Lucknowi Dum Biryani is prepared using the traditional dum cooking method, where basmati rice and marinated meat are layered and slow-cooked together to lock in rich flavors and aroma. Made with fresh ingredients, mild spices, saffron, and desi ghee, it offers a perfectly balanced taste that is not too spicy but full of authentic Awadhi flavor.",
    gst: 9043898996702,
    fssai: 789347370000,
    totalRatings: 320,
    followers: 5200,
    products: 250,
    showAdd: false,
  },

  {
    id: 3,
    title: "Restaurant",
    subtitle: "Mughlai & Awadhi Cuisine",
    address: "Hazratganj, Lucknow",
    phone: "+91 97930 00003",
    category: "Fine Dine Restaurant",
    image: dastarkhwanImg,
    logo: dastarkhwanLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Close",
    rating: 4.4,
    gst: 9043898996703,
    totalRatings: 180,
    followers: 3000,
    products: 200,
    showAdd: true,
  },

  {
    id: 4,
    title: "Restaurant",
    subtitle: "Basket Chaat Special",
    address: "Hazratganj, Lucknow",
    phone: "+91 97930 00004",
    category: "Veg Restaurant",
    image: royalCafeImg,
    logo: royalCafeLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.7,
    gst: 9043898996704,
    totalRatings: 400,
    followers: 6000,
    products: 280,
    showAdd: false,
  },

  {
    id: 5,
    title: "Restaurant",
    subtitle: "Classic Family Dining",
    address: "Indira Nagar, Lucknow",
    phone: "+91 97930 00005",
    category: "Multi-Cuisine",
    image: marksmenImg,
    logo: marksmenLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.2,
    gst: 9043898996705,
    totalRatings: 150,
    followers: 2400,
    products: 160,
    showAdd: true,
  },

  {
    id: 6,
    title: "Restaurant",
    subtitle: "Traditional Nihari House",
    address: "Akbari Gate, Lucknow",
    phone: "+91 97930 00006",
    category: "Non-Veg Restaurant",
    image: rahimImg,
    logo: rahimLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.5,
    gst: 9043898996706,
    totalRatings: 260,
    followers: 4200,
    products: 210,
    showAdd: false,
  },

  {
    id: 7,
    title: "Restaurant",
    subtitle: "Mutton & Chicken Special",
    address: "Chowk, Lucknow",
    phone: "+91 97930 00007",
    category: "Non-Veg Restaurant",
    image: mubeensImg,
    logo: mubeensLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Close",
    rating: 4.1,
    gst: 9043898996707,
    totalRatings: 130,
    followers: 2100,
    products: 140,
    showAdd: true,
  },

  {
    id: 8,
    title: "Restaurant",
    subtitle: "Pure Veg & Snacks",
    address: "Alambagh, Lucknow",
    phone: "+91 97930 00008",
    category: "Veg Restaurant",
    image: kalikaImg,
    logo: kalikaLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.3,
    gst: 9043898996708,
    totalRatings: 190,
    followers: 3300,
    products: 180,
    showAdd: false,
  },

  {
    id: 9,
    title: "Restaurant",
    subtitle: "Chicken Korma Special",
    address: "Gomti Nagar, Lucknow",
    phone: "+91 97930 00009",
    category: "Non-Veg Restaurant",
    image: tundayImg,
    logo: tundayLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.5,
    gst: 9043898996709,
    totalRatings: 275,
    followers: 4500,
    products: 220,
    showAdd: true,
  },

  {
    id: 10,
    title: "Restaurant",
    subtitle: "Hyderabadi Biryani Feast",
    address: "Mahanagar, Lucknow",
    phone: "+91 97930 00010",
    category: "Biryani Restaurant",
    image: idreesImg,
    logo: idreesLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Close",
    rating: 4.2,
    gst: 9043898996710,
    totalRatings: 160,
    followers: 2600,
    products: 150,
    showAdd: false,
  },

  {
    id: 11,
    title: "Restaurant",
    subtitle: "Paneer Butter Masala",
    address: "Rajajipuram, Lucknow",
    phone: "+91 97930 00011",
    category: "Veg Restaurant",
    image: royalCafeImg,
    logo: royalCafeLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.6,
    gst: 9043898996711,
    totalRatings: 240,
    followers: 4100,
    products: 210,
    showAdd: true,
  },

  {
    id: 12,
    title: "Restaurant",
    subtitle: "Chicken Tandoori",
    address: "Mahanagar, Lucknow",
    phone: "+91 97930 00012",
    category: "Non-Veg Restaurant",
    image: mubeensImg,
    logo: mubeensLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.3,
    gst: 9043898996712,
    totalRatings: 175,
    followers: 2800,
    products: 160,
    showAdd: false,
  },

  {
    id: 13,
    title: "Restaurant",
    subtitle: "Veg Fried Rice",
    address: "Alambagh, Lucknow",
    phone: "+91 97930 00013",
    category: "Veg Restaurant",
    image: kalikaImg,
    logo: kalikaLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Close",
    rating: 4.1,
    gst: 9043898996713,
    totalRatings: 140,
    followers: 2000,
    products: 120,
    showAdd: true,
  },

  {
    id: 14,
    title: "Restaurant",
    subtitle: "Mutton Seekh Kebab",
    address: "Chowk, Lucknow",
    phone: "+91 97930 00014",
    category: "Non-Veg Restaurant",
    image: rahimImg,
    logo: rahimLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.4,
    gst: 9043898996714,
    totalRatings: 165,
    followers: 2500,
    products: 135,
    showAdd: false,
  },

  {
    id: 15,
    title: "Restaurant",
    subtitle: "Grand Dinner Special",
    address: "Gomti Nagar, Lucknow",
    phone: "+91 97930 00015",
    category: "Multi-Cuisine",
    image: dastarkhwanImg,
    logo: dastarkhwanLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.9,
    gst: 9043898996715,
    totalRatings: 400,
    followers: 7200,
    products: 350,
    showAdd: true,
  },

  {
    id: 16,
    title: "Restaurant",
    subtitle: "Special Veg Thali",
    address: "Indira Nagar, Lucknow",
    phone: "+91 97930 00016",
    category: "Veg Restaurant",
    image: royalCafeImg,
    logo: royalCafeLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.0,
    gst: 9043898996716,
    totalRatings: 130,
    followers: 1900,
    products: 100,
    showAdd: false,
  },

  {
    id: 17,
    title: "Restaurant",
    subtitle: "Butter Chicken Deluxe",
    address: "Hazratganj, Lucknow",
    phone: "+91 97930 00017",
    category: "Non-Veg Restaurant",
    image: tundayImg,
    logo: tundayLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Close",
    rating: 4.7,
    gst: 9043898996717,
    totalRatings: 260,
    followers: 4800,
    products: 220,
    showAdd: true,
  },

  {
    id: 18,
    title: "Restaurant",
    subtitle: "Special Chaat Platter",
    address: "Alambagh, Lucknow",
    phone: "+91 97930 00018",
    category: "Veg Restaurant",
    image: kalikaImg,
    logo: kalikaLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.2,
    gst: 9043898996718,
    totalRatings: 150,
    followers: 2300,
    products: 140,
    showAdd: false,
  },

  {
    id: 19,
    title: "Restaurant",
    subtitle: "Chicken Roll Special",
    address: "Aminabad, Lucknow",
    phone: "+91 97930 00019",
    category: "Non-Veg Restaurant",
    image: mubeensImg,
    logo: mubeensLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.3,
    gst: 9043898996719,
    totalRatings: 175,
    followers: 2600,
    products: 150,
    showAdd: true,
  },

  {
    id: 20,
    title: "Restaurant",
    subtitle: "Veg Deluxe Combo",
    address: "Rajajipuram, Lucknow",
    phone: "+91 97930 00020",
    category: "Veg Restaurant",
    image: royalCafeImg,
    logo: royalCafeLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Close",
    rating: 4.5,
    gst: 9043898996720,
    totalRatings: 200,
    followers: 3000,
    products: 180,
    showAdd: false,
  },

  {
    id: 21,
    title: "Restaurant",
    subtitle: "Mutton Curry Special",
    address: "Chowk, Lucknow",
    phone: "+91 97930 00021",
    category: "Non-Veg Restaurant",
    image: rahimImg,
    logo: rahimLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.6,
    gst: 9043898996721,
    totalRatings: 290,
    followers: 5000,
    products: 240,
    showAdd: true,
  },

  {
    id: 22,
    title: "Restaurant",
    subtitle: "Family Biryani Pack",
    address: "Indira Nagar, Lucknow",
    phone: "+91 97930 00022",
    category: "Biryani Restaurant",
    image: idreesImg,
    logo: idreesLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.4,
    gst: 9043898996722,
    totalRatings: 220,
    followers: 3600,
    products: 210,
    showAdd: false,
  },

  {
    id: 23,
    title: "Restaurant",
    subtitle: "Veg Party Pack",
    address: "Hazratganj, Lucknow",
    phone: "+91 97930 00023",
    category: "Veg Restaurant",
    image: kalikaImg,
    logo: kalikaLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Close",
    rating: 4.1,
    gst: 9043898996723,
    totalRatings: 140,
    followers: 2100,
    products: 130,
    showAdd: true,
  },

  {
    id: 24,
    title: "Restaurant",
    subtitle: "Chicken Special Combo",
    address: "Mahanagar, Lucknow",
    phone: "+91 97930 00024",
    category: "Non-Veg Restaurant",
    image: rahimImg,
    logo: rahimLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 4.8,
    gst: 9043898996724,
    totalRatings: 310,
    followers: 6200,
    products: 300,
    showAdd: false,
  },

  {
    id: 25,
    title: "Restaurant",
    subtitle: "Royal Dinner Feast",
    address: "Gomti Nagar, Lucknow",
    phone: "+91 97930 00025",
    category: "Multi-Cuisine",
    image: dastarkhwanImg,
    logo: dastarkhwanLogo,
    categoryLink: "#",
    cardLink: "#",
    status: "Open",
    rating: 5.0,
    gst: 9043898996725,
    totalRatings: 500,
    followers: 9000,
    products: 400,
    showAdd: true,
  },

];

export default Featured;
