import kaju1 from "../../assets/kaju1.jpg";
import kaju2 from "../../assets/kaju1.jpg";
import kaju3 from "../../assets/kaju1.jpg";
import kaju4 from "../../assets/kaju1.jpg";
import kaju5 from "../../assets/kaju1.jpg";

const KajuNamkeens = [
  {
    id: 1,
    image: kaju1,
    images: [kaju1, kaju2, kaju3, kaju4],
    title: "Kaju Mix",
    portion: "250 Gram",
    desc: "Kaju Mix is a premium blend of crunchy cashews, golden raisins, and lightly spiced savory elements. Each bite delivers a rich, nutty flavor with a perfect balance of sweet and salty. Ideal for festive occasions, gifting, or daily snacking, packed fresh to retain crispiness and aroma.",
    rating: "4.9",
    reviews: "7.2k",
    orders: "1200",
    status: "Open - Close at 10:30pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: "3.2k",
    type: "veg",
    price: 299,
    offer: 349,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 2,
    image: kaju2,
    images: [kaju2, kaju1, kaju3, kaju5],
    title: "Hari Mix",
    portion: "200 Gram",
    desc: "Hari Mix is a refreshing, green-herb infused nut mix featuring crunchy cashews and lightly roasted pulses. Aromatic herbs like coriander and mint enhance the flavor, creating a deliciously healthy and satisfying snack. Perfect for teatime or as a nutritious on-the-go option.",
    rating: "4.8",
    reviews: "6.8k",
    orders: "1050",
    status: "Open - Close at 11:00pm",
    slots: ["10:30-11:30", "12:30-1:30", "2:30-3:30"],
    isOpen: true,
    view: "2.8k",
    type: "veg",
    price: 249,
    offer: 299,
    off: 17,
    restaurantId: 2,
  },
  {
    id: 3,
    image: kaju3,
    images: [kaju3, kaju2, kaju4, kaju1],
    title: "Hari Pudina Kaju",
    portion: "250 Gram",
    desc: "Hari Pudina Kaju combines crunchy cashews with aromatic mint leaves, creating a vibrant and refreshing flavor. Lightly spiced and roasted to perfection, it is ideal for festive snacking, gifting, or enjoying as a wholesome treat with tea or coffee.",
    rating: "4.9",
    reviews: "7.0k",
    orders: "1120",
    status: "Open - Close at 10:30pm",
    slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
    isOpen: true,
    view: "3.0k",
    type: "veg",
    price: 279,
    offer: 329,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 4,
    image: kaju4,
    images: [kaju4, kaju1, kaju5, kaju2],
    title: "Palak Kaju",
    portion: "250 Gram",
    desc: "Palak Kaju is a unique nut mix enriched with the goodness of fresh spinach powder and lightly roasted cashews. It offers a subtle earthy flavor with a crunchy texture, perfect for health-conscious snack lovers. Enjoy it as a guilt-free indulgence anytime.",
    rating: "4.8",
    reviews: "6.5k",
    orders: "980",
    status: "Open - Close at 11:00pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: "2.6k",
    type: "veg",
    price: 289,
    offer: 339,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 5,
    image: kaju5,
    images: [kaju5, kaju3, kaju2, kaju1],
    title: "Kashmiri Kaju",
    portion: "200 Gram",
    desc: "Kashmiri Kaju features premium cashews combined with aromatic Kashmiri spices and a touch of saffron. Each bite is rich, flavorful, and slightly sweet, delivering a festive snack experience that is perfect for gifting, tea-time, or celebration occasions.",
    rating: "5.0",
    reviews: "7.5k",
    orders: "1250",
    status: "Open - Close at 10:30pm",
    slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
    isOpen: true,
    view: "3.4k",
    type: "veg",
    price: 319,
    offer: 369,
    off: 14,
    restaurantId: 2,
  },
  {
  id: 6,
  image: kaju1,
  images: [kaju1, kaju2, kaju3, kaju4],
  title: "Pudina Kaju",
  portion: "250 Gram",
  desc: "Pudina Kaju is a refreshing and flavorful premium cashew snack infused with natural mint essence and aromatic Indian spices. Carefully roasted to golden perfection, each cashew delivers a crisp texture combined with a cool minty finish. The balanced blend of mild spice and fresh pudina flavor makes it an ideal snack for summer evenings, festive gatherings, and tea-time moments. Hygienically packed to preserve freshness and crunch.",
  rating: "4.9",
  reviews: "8.1k",
  orders: "1350",
  status: "Open - Close at 10:30pm",
  slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
  isOpen: true,
  view: "3.6k",
  type: "veg",
  price: 289,
  offer: 339,
  off: 15,
  restaurantId: 2,
},

{
  id: 7,
  image: kaju2,
  images: [kaju2, kaju3, kaju4, kaju1],
  title: "Masala Kaju",
  portion: "250 Gram",
  desc: "Masala Kaju is prepared using premium whole cashews coated with a bold and spicy masala blend. Roasted evenly for maximum crunch, this snack delivers a rich combination of tangy, spicy, and savory flavors in every bite. Perfect for spice lovers and festive occasions, it pairs beautifully with tea, coffee, and party platters.",
  rating: "4.8",
  reviews: "7.6k",
  orders: "1180",
  status: "Open - Close at 11:00pm",
  slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
  isOpen: true,
  view: "3.1k",
  type: "veg",
  price: 299,
  offer: 349,
  off: 14,
  restaurantId: 2,
},

{
  id: 8,
  image: kaju3,
  images: [kaju3, kaju1, kaju2, kaju5],
  title: "Salted Kaju",
  portion: "200 Gram",
  desc: "Salted Kaju is a timeless classic made from carefully selected premium cashews lightly roasted and seasoned with fine salt. The simple yet rich flavor highlights the natural creaminess of cashews while offering a satisfying crunch. Ideal for daily snacking, gifting, and serving guests during special occasions.",
  rating: "4.7",
  reviews: "6.4k",
  orders: "960",
  status: "Open - Close at 10:30pm",
  slots: "",
  isOpen: true,
  view: "2.4k",
  type: "veg",
  price: 259,
  offer: 299,
  off: 13,
  restaurantId: 2,
},

{
  id: 9,
  image: kaju4,
  images: [kaju4, kaju2, kaju3, kaju1],
  title: "Black Pepper Kaju",
  portion: "250 Gram",
  desc: "Black Pepper Kaju is a premium snack featuring crunchy cashews coated with freshly ground black pepper and mild spices. The bold peppery aroma combined with the natural sweetness of cashews creates a unique and satisfying taste experience. Perfect for those who enjoy strong, sharp flavors with a crunchy texture.",
  rating: "4.8",
  reviews: "7.0k",
  orders: "1100",
  status: "Open - Close at 11:00pm",
  slots: "",
  isOpen: true,
  view: "2.9k",
  type: "veg",
  price: 309,
  offer: 359,
  off: 14,
  restaurantId: 2,
},

{
  id: 10,
  image: kaju5,
  images: [kaju5, kaju3, kaju2, kaju1],
  title: "Special Dry Fruit Kaju",
  portion: "300 Gram",
  desc: "Special Dry Fruit Kaju is a luxurious blend of premium cashews combined with select dry fruits and aromatic spices. Carefully roasted for enhanced crunch and rich flavor, this festive snack offers a perfect balance of sweetness and savory taste. Ideal for gifting, celebrations, and premium snack platters, it is packed fresh to maintain quality and freshness.",
  rating: "5.0",
  reviews: "9.3k",
  orders: "1500",
  status: "Open - Close at 11:00pm",
  slots: ["10:30-11:30", "12:30-1:30", "2:30-3:30"],
  isOpen: true,
  view: "4.1k",
  type: "veg",
  price: 399,
  offer: 459,
  off: 13,
  restaurantId: 2,
},

];

export default KajuNamkeens;
