import sev1 from "../../assets/sev.jpg";
import sev2 from "../../assets/sev.jpg";
import sev3 from "../../assets/sev.jpg";
import sev4 from "../../assets/sev.jpg";
import sev5 from "../../assets/sev.jpg";
import sev6 from "../../assets/sev.jpg";
import sev7 from "../../assets/sev.jpg";
import sev8 from "../../assets/sev.jpg";

const SevList = [
  {
    id: 1,
    image: sev1,
    images: [sev1, sev2, sev3, sev4],
    title: "Lal Sev",
    portion: "250 Gram",
    desc: "Lal Sev is a vibrant and spicy traditional snack made with golden gram flour noodles fried to perfection. Each crispy bite is coated with a bold, tangy masala blend that gives it a fiery flavor. Perfect for tea-time snacking, festive occasions, or as an accompaniment to chaat dishes. Carefully packed to retain crunchiness and freshness for daily indulgence.",
    rating: 4.9,
    reviews: "10k",
    orders: "1500",
    status: "Open - Close at 11:00pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: 900,
    type: "veg",
    price: 159,
    offer: 199,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 2,
    image: sev2,
    images: [sev2, sev3, sev4, sev1],
    title: "Methi Sev",
    portion: "250 Gram",
    desc: "Methi Sev is a crunchy and aromatic snack infused with the subtle bitterness of fenugreek leaves combined with traditional Indian spices. Perfect for tea-time, evening snacks, or topping for chaats. It delivers a satisfying crisp and bold flavor in every bite, carefully packed for freshness.",
    rating: 4.8,
    reviews: "9.5k",
    orders: "1400",
    status: "Open - Close at 11:00pm",
    slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
    isOpen: true,
    view: 850,
    type: "veg",
    price: 149,
    offer: 179,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 3,
    image: sev3,
    images: [sev3, sev4, sev1, sev2],
    title: "Papdee",
    portion: "250 Gram",
    desc: "Papdee is a crunchy and light snack made from refined flour and carefully fried to a perfect crisp. Lightly spiced, it is ideal for making chaats or enjoying as a standalone snack. Its thin and crispy texture along with mild tangy flavor makes it irresistible and perfect for festive occasions or casual munching.",
    rating: 4.7,
    reviews: "8.8k",
    orders: "1200",
    status: "Open - Close at 10:30pm",
    slots: ["10:30-11:30", "12:30-1:30"],
    isOpen: true,
    view: 780,
    type: "veg",
    price: 139,
    offer: 169,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 4,
    image: sev4,
    images: [sev4, sev1, sev2, sev3],
    title: "Ratlami Sev",
    portion: "250 Gram",
    desc: "Ratlami Sev is a traditional specialty from Ratlam, made with premium chickpea flour and hand-spiced with a blend of aromatic Indian spices. Its crispy texture and rich masala coating deliver an authentic snack experience. Perfect for tea-time, street food chaat, or festive celebrations, this sev is hygienically packed to maintain its freshness.",
    rating: 4.9,
    reviews: "10.2k",
    orders: "1600",
    status: "Open - Close at 11:00pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: 950,
    type: "veg",
    price: 169,
    offer: 199,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 5,
    image: sev5,
    images: [sev5, sev6, sev7, sev8],
    title: "Heeng Sev",
    portion: "250 Gram",
    desc: "Heeng Sev is a crunchy and aromatic snack enriched with pure asafoetida (heeng), giving it a distinctive flavor. Made with fine gram flour and fried to perfection, this sev is perfect for tea-time, evening munching, or as a topping for chaats. Its bold aroma and crisp texture make it an irresistible snack for all ages.",
    rating: 4.8,
    reviews: "9.8k",
    orders: "1300",
    status: "Open - Close at 10:30pm",
    slots: ["11:00-12:00", "1:00-2:00"],
    isOpen: true,
    view: 820,
    type: "veg",
    price: 149,
    offer: 179,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 6,
    image: sev6,
    images: [sev6, sev7, sev8, sev5],
    title: "Gathiya",
    portion: "250 Gram",
    desc: "Gathiya is a soft and crunchy snack made from chickpea flour and lightly fried to perfection. Mildly spiced with traditional Indian masalas, it is perfect for tea-time or casual snacking. Its rich texture and soft bite combined with aromatic flavors make it a favorite across all age groups.",
    rating: 4.7,
    reviews: "9.2k",
    orders: "1250",
    status: "Open - Close at 10:30pm",
    slots: ["10:30-11:30", "1:30-2:30"],
    isOpen: true,
    view: 780,
    type: "veg",
    price: 139,
    offer: 169,
    off: 15,
    restaurantId: 2,
  },
  //   {
  //     id: 7,
  //     image: sev7,
  //     images: [sev7, sev8, sev5, sev6],
  //     title: "Lehsun Sev",
  //     portion: "250 Gram",
  //     desc: "Lehsun Sev is a flavorful snack infused with roasted garlic (lehsun) and traditional spices, delivering a bold, aromatic, and crunchy experience. Perfect for tea-time, chaats, or festive snacking. Carefully packed to maintain freshness, texture, and taste for everyday enjoyment.",
  //     rating: 4.8,
  //     reviews: "9.5k",
  //     orders: "1280",
  //     status: "Open - Close at 11:00pm",
  //     slots: ["11:00-12:00", "1:00-2:00"],
  //     isOpen: true,
  //     view: 800,
  //     type: "veg",
  //     price: 159,
  //     offer: 199,
  //     off: 15,
  //     restaurantId: 2,
  //   },
  //   {
  //     id: 8,
  //     image: sev8,
  //     images: [sev8, sev5, sev6, sev7],
  //     title: "Makka Sev",
  //     portion: "250 Gram",
  //     desc: "Makka Sev is a traditional crunchy snack made from corn flour, lightly fried and seasoned with subtle Indian spices. Its golden color and crisp texture make it perfect for tea-time, festive occasions, or enjoying as a standalone snack. Hygienically packed to retain freshness and provide an authentic taste in every bite.",
  //     rating: 4.7,
  //     reviews: "9k",
  //     orders: "1200",
  //     status: "Open - Close at 10:30pm",
  //     slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
  //     isOpen: true,
  //     view: 770,
  //     type: "veg",
  //     price: 149,
  //     offer: 179,
  //     off: 15,
  //     restaurantId: 2,
  //   },
  //   {
  //   id: 9,
  //   image: sev1, // you can replace with a new image if available
  //   images: [sev1, sev3, sev5, sev7],
  //   title: "Masala Sev",
  //   portion: "250 Gram",
  //   desc: "Masala Sev is a spicy and crunchy snack made from premium gram flour noodles, blended with a perfect mix of traditional Indian spices. Each bite delivers a bold and tangy flavor that is perfect for tea-time, evening munching, or as a topping for chaats. Hygienically packed to maintain freshness, crispiness, and authentic taste for everyday snacking.",
  //   rating: 4.9,
  //   reviews: "11k",
  //   orders: "1600",
  //   status: "Open - Close at 11:00pm",
  //   slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
  //   isOpen: true,
  //   view: 980,
  //   type: "veg",
  //   price: 169,
  //   offer: 199,
  //   off: 15,
  //   restaurantId: 2,
  // },
  // {
  //   id: 10,
  //   image: sev2, // you can replace with a new image if available
  //   images: [sev2, sev4, sev6, sev8],
  //   title: "Chili Sev",
  //   portion: "250 Gram",
  //   desc: "Chili Sev is a fiery and crunchy snack made from golden gram flour strands, coated with a special blend of chili spices. Perfect for spice lovers who enjoy bold flavors, it is ideal for tea-time, snacking, or adding an extra kick to your favorite chaats. Packed with care to maintain its crispiness and vibrant flavor.",
  //   rating: 4.8,
  //   reviews: "10.5k",
  //   orders: "1500",
  //   status: "Open - Close at 10:30pm",
  //   slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
  //   isOpen: true,
  //   view: 920,
  //   type: "veg",
  //   price: 159,
  //   offer: 189,
  //   off: 15,
  //   restaurantId: 2,
  // }

];

export default SevList;
