import food_1 from "../../assets/namkeen1.png";
import nm1 from "../../assets/namkeen2.png";
import nm2 from "../../assets/namkeen3.png";
import nm3 from "../../assets/namkeen4.png";
import nm4 from "../../assets/namkeen5.png";
import nm5 from "../../assets/namkeen6.png";
import nm6 from "../../assets/namkeen7.png";
import nm7 from "../../assets/namkeen8.png";

const ShyamList = [
  {
    id: 1,
    image: food_1,
    images: [food_1, nm2, nm3, nm4],
    title: "Disco Namkeen",
    portion: "250 Gram",
    desc: "Disco Namkeen is a colorful and crunchy traditional snack made with a vibrant blend of crispy sev, fried lentils, peanuts, and flavorful Indian spices. Its perfectly balanced spicy coating and rich texture make every bite exciting and satisfying. Carefully prepared and hygienically packed to maintain freshness, this namkeen is ideal for tea-time, festive occasions, travel, and everyday snacking.",
    rating: "4.9",
    reviews: "10.2k",
    orders: "1500",
    status: "Open - Close at 11:00pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,

    view: 900,
    type: "veg",
    price: 159,
    deliveryTime: "20-30 min",
    offer: 199,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 2,
    image: nm1,
    images: [nm2, nm3, nm4, food_1],
    title: "Hari Masoor",
    portion: "500 Gram",
    desc: "Hari Masoor is prepared using premium quality green lentils that are fried to golden perfection for a crisp and crunchy texture. Lightly seasoned with traditional spices, it offers a wholesome and protein-rich snacking option. Its natural earthy flavor and balanced taste make it a healthy yet delicious choice for daily munching.",
    rating: "4.7",
    reviews: "5.4k",
    orders: "780",
    status: "Open - Close at 10:30pm",
    isOpen: true,
    view: "1.4k",
    type: "veg",
    price: 209,
    offer: 259,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 3,
    image: nm2,
    images: [nm3, nm2, nm4, food_1],
    title: "Heeng  Papdee",
    portion: "250 Gram",
    desc: "Heeng Papdee is a crispy and aromatic snack infused with the strong and distinctive flavor of pure asafoetida (heeng). Made from refined flour and blended spices, it delivers a bold, tangy, and slightly spicy taste in every crunchy bite. Perfect for serving with tea or enhancing chaat dishes with extra flavor and crispiness.",
    rating: "4.8",
    reviews: "6.3k",
    orders: "890",
    status: "Open - Close at 10:30pm",
    slots: ["11:00-11:30", "12:00-12:30", "2:00-3:00"],
    isOpen: false,
    view: "1.9k",
    type: "veg",
    price: 139,
    offer: 179,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 4,
    image: nm3,
    images: [nm4, nm2, nm3, food_1],
    title: "Jal Jeera",
    portion: "500 Gram",
    desc: "Jal Jeera Namkeen is inspired by the refreshing and tangy taste of traditional jal jeera masala. Coated with mint essence, cumin, and zesty spices, it delivers a chatpata and refreshing flavor experience. Its light crunch and tangy seasoning make it a perfect snack for summer evenings and festive gatherings.",
    rating: "4.8",
    reviews: "6.8k",
    orders: "1020",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "2.5k",
    type: "veg",
    price: 189,
    offer: 229,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 5,
    image: nm4,
    images: [nm3, nm2, nm4, food_1],
    title: "Laccha Moongfali",
    portion: "1 Kg",
    desc: "Laccha Moongfali features high-quality peanuts coated with crispy gram flour strands and traditional spicy masala. The layered texture provides an extra crunch, while the bold seasoning enhances the overall taste. Ideal for parties, celebrations, and daily snacking, this namkeen is packed fresh to retain its crispiness.",
    rating: "4.6",
    reviews: "4.2k",
    orders: "610",
    status: "Close - Open at 08:00pm",
    slots: "",
    isOpen: false,
    view: "1.8k",
    type: "veg",
    price: 459,
    offer: 599,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 6,
    image: nm5,
    images: [nm1, nm2, nm4, food_1],
    title: "Madrasi",
    portion: "500 Gram",
    desc: "Madrasi Namkeen is a South Indian-style crispy snack prepared with gram flour and authentic regional spices. Its bold, slightly spicy flavor combined with a crunchy texture delivers a traditional southern taste experience. Perfect for festive occasions, evening tea, and those who love strong and spicy snacks.",
    rating: "4.9",
    reviews: "7.1k",
    orders: "1120",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "2.9k",
    type: "veg",
    price: 309,
    offer: 369,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 7,
    image: nm6,
    images: [nm1, nm2, nm3, nm4],
    title: "Special Masoor",
    portion: "250 Gram",
    desc: "Special Masoor is crafted from carefully selected lentils that are fried until golden and perfectly crisp. Lightly salted and mildly spiced, it offers a crunchy texture with a rich and satisfying taste. This protein-rich snack is ideal for health-conscious customers who want both nutrition and flavor.",
    rating: "4.7",
    reviews: "5.8k",
    orders: "870",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: false,
    view: "1.5k",
    type: "veg",
    price: 149,
    offer: 189,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 8,
    image: nm7,
    images: [nm2, nm3, nm4, food_1],
    title: "Bambaiya Mix",
    portion: "500 Gram",
    desc: "Bambaiya Mix is a Mumbai-style spicy mixture made with crispy sev, flattened rice, peanuts, fried lentils, and bold masalas. It delivers a street-style chatpata flavor with the perfect balance of spice and crunch. Ideal for tea-time, gatherings, and those who love authentic Mumbai taste.",
    rating: "4.6",
    reviews: "4.9k",
    orders: "720",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.3k",
    type: "veg",
    price: 179,
    offer: 219,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 9,
    image: food_1,
    images: [nm3, nm4, nm1, food_1],
    title: "Chavani",
    portion: "250 Gram",
    desc: "Infused with the rich aroma of garlic and special spices, Shyam Lahsun Sev delivers a bold and flavorful snacking experience. Perfect for those who enjoy strong and spicy flavors in every crunchy bite.",
    rating: "4.8",
    reviews: "6.5k",
    orders: "990",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "2.1k",
    type: "veg",
    price: 159,
    offer: 199,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 10,
    image: nm1,
    images: [nm4, nm3, nm2, food_1],
    title: "Bombay Masala",
    portion: "500 Gram",
    desc: "Bombay Masala is a spicy and flavorful mixture made with crunchy sev, peanuts, flattened rice, and special Bombay-style masalas. It delivers a bold and slightly fiery taste that spice lovers truly enjoy. Freshly packed to preserve crunch and flavor, it is ideal for evening snacks and festive moments.",
    rating: "4.7",
    reviews: "5.6k",
    orders: "860",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.9k",
    type: "veg",
    price: 229,
    offer: 279,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 11,
    image: nm2,
    images: [nm5, nm2, nm3, food_1],
    title: "Punchratan",
    portion: "500 Gram",
    desc: "Punchratan is a premium five-element mixture combining crunchy sev, fried lentils, peanuts, cashews, and raisins blended with aromatic spices. The mix of sweet, salty, and spicy flavors creates a rich and festive taste experience. Perfect for celebrations, gifting, and special family gatherings.",
    rating: "4.9",
    reviews: "7.4k",
    orders: "1100",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "3.2k",
    type: "veg",
    price: 399,
    offer: 459,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 12,
    image: nm3,
    images: [nm6, nm3, nm2, food_1],
    title: "Gujrati Cornflcs",
    portion: "250 Gram",
    desc: "Gujrati Cornflakes is a light and crispy mixture made from golden cornflakes, roasted peanuts, curry leaves, and mild Gujarati-style spices. It offers a balanced sweet and savory taste that is less oily and highly crunchy. A perfect option for those who prefer light yet flavorful snacking.",
    rating: "4.6",
    reviews: "4.4k",
    orders: "690",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.2k",
    type: "veg",
    price: 149,
    offer: 189,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 13,
    image: nm4,
    images: [nm1, nm4, nm2, food_1],
    title: "Lal Navratan",
    portion: "250 Gram",
    desc: "Lal Navratan is a rich and colorful festive mixture made with premium sev, nuts, lentils, and flavorful spices. Its vibrant red masala coating adds extra spice and depth to every bite. Designed for celebrations and special occasions, it offers multiple textures and bold flavors in one pack.",
    rating: "4.8",
    reviews: "6.9k",
    orders: "980",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "2.6k",
    type: "veg",
    price: 199,
    offer: 249,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 14,
    image: nm5,
    images: [nm2, nm5, nm3, food_1],
    title: "Navrang Mix",
    portion: "500 Gram",
    desc: "Navrang Mix is a multi-textured namkeen blend combining crispy sev, crunchy pulses, peanuts, and flavorful spices. True to its name, it offers a variety of tastes and textures in every handful. Ideal for festive celebrations, tea-time snacks, and family gatherings.",
    rating: "4.7",
    reviews: "5.3k",
    orders: "820",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.8k",
    type: "veg",
    price: 249,
    offer: 299,
    off: 17,
    restaurantId: 2,
  },
  {
    id: 15,
    image: nm6,
    images: [nm3, nm6, nm2, food_1],
    title: "Kastori Mix",
    portion: "500 Gram",
    desc: "Kastori Mix is a flavorful and aromatic namkeen mixture prepared with premium ingredients and special spice blends. It delivers a balanced taste with crunchy textures and a mildly spicy finish. Perfect for those who enjoy traditional flavors with a rich and satisfying crunch.",
    rating: "4.6",
    reviews: "4.7k",
    orders: "740",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.6k",
    type: "veg",
    price: 219,
    offer: 269,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 16,
    image: nm7,
    images: [nm4, nm3, nm1, food_1],
    title: "Makhana Laccha",
    portion: "250 Gram",
    desc: "Makhana Laccha combines crispy fox nuts (makhana) with layered gram flour strands and light spices for a unique crunchy experience. It offers a lighter yet flavorful snacking option packed with texture and taste. Ideal for health-conscious individuals who want a delicious and wholesome snack.",
    rating: "4.8",
    reviews: "6.1k",
    orders: "910",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "2.3k",
    type: "veg",
    price: 169,
    offer: 209,
    off: 19,
    restaurantId: 2,
  },
  {
    id: 17,
    image: food_1,
    images: [nm5, nm2, nm4, food_1],
    title: "Dehati Namkeen",
    portion: "500 Gram",
    desc: "Dehati Namkeen delivers a rustic and traditional village-style taste made with simple yet flavorful ingredients. Its crunchy texture and bold desi spices create an authentic Indian snacking experience. Perfect for those who love classic homemade-style namkeen flavors.",
    rating: "4.7",
    reviews: "5.9k",
    orders: "880",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "2.0k",
    type: "veg",
    price: 199,
    offer: 239,
    off: 16,
    restaurantId: 2,
  },
  {
    id: 18,
    image: nm1,
    images: [nm6, nm3, nm1, food_1],
    title: "Moong Mix",
    portion: "250 Gram",
    desc: "Moong Mix is prepared using crispy fried moong dal blended with peanuts, sev, and light spices. It offers a protein-rich, crunchy, and mildly spicy taste that makes it ideal for daily snacking. Freshly packed to maintain crispiness, it is both tasty and satisfying.",
    rating: "4.6",
    reviews: "4.5k",
    orders: "710",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.5k",
    type: "veg",
    price: 159,
    offer: 199,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 19,
    image: nm2,
    images: [nm1, nm4, nm2, food_1],
    title: "Heemg Jeera",
    portion: "250 Gram",
    desc: "Heemg Jeera Namkeen is infused with the strong aroma of asafoetida (heeng) and the earthy flavor of roasted cumin (jeera). Its crispy texture combined with bold and tangy spices delivers a unique and authentic taste. Perfect for those who enjoy traditional Indian spice profiles.",
    rating: "4.9",
    reviews: "7.8k",
    orders: "1200",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "3.5k",
    type: "veg",
    price: 179,
    offer: 219,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 20,
    image: nm3,
    images: [nm2, nm3, nm5, food_1],
    title: "Chaska Masala",
    portion: "1 Kg",
    desc: "Chaska Masala is a bold and spicy namkeen blend prepared with crunchy sev, pulses, and signature chaska masala seasoning. Every bite delivers a flavorful punch with a perfect balance of spice and crunch. Ideal for spice lovers, parties, and festive snacking moments.",
    rating: "5.0",
    reviews: "9.1k",
    orders: "1400",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "4.0k",
    type: "veg",
    price: 599,
    offer: 749,
    off: 20,
    restaurantId: 2,
  },
];

export default ShyamList;
