// ShyamBhujiyaData.jsx
import bhujiya1 from "../../assets/bhujiya1.jpg";
import bhujiya2 from "../../assets/bhujiya1.jpg";
import bhujiya3 from "../../assets/bhujiya1.jpg";
import bhujiya4 from "../../assets/bhujiya1.jpg";
import bhujiya5 from "../../assets/bhujiya1.jpg";
import bhujiya6 from "../../assets/bhujiya1.jpg";
import bhujiya7 from "../../assets/bhujiya1.jpg";

const ShyamBhujiyaData = [
  {
    id: 1,
    image: bhujiya1,
    images: [bhujiya1, bhujiya2, bhujiya3, bhujiya4],
    title: "Aloo Bhujiya",
    portion: "200 Gram",
    desc: "Aloo Bhujiya is made from thin, crispy potato strands perfectly fried and lightly spiced. Each bite offers a crunchy texture with a balanced savory flavor. Ideal for tea-time, parties, and festive occasions, packed to maintain freshness and crispiness.",
    rating: "4.8",
    reviews: "6.0k",
    orders: "900",
    status: "Open - Close at 10:30pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: "2.0k",
    type: "veg",
    price: 109,
    deliveryTime: "20-30 min",
    offer: 139,
    off: 21,
    restaurantId: 2,
  },
  {
    id: 2,
    image: bhujiya2,
    images: [bhujiya2, bhujiya3, bhujiya4, bhujiya1],
    title: "Paneer Bhujiya",
    portion: "250 Gram",
    desc: "Paneer Bhujiya combines delicate strands of potato with finely spiced paneer pieces for a unique taste. Crispy, flavorful, and mildly spiced, it is perfect for snacking at home, parties, or festive occasions.",
    rating: "4.9",
    reviews: "6.5k",
    orders: "1050",
    status: "Open - Close at 11:00pm",
    slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
    isOpen: true,
    view: "2.5k",
    type: "veg",
    price: 129,
    offer: 159,
    off: 19,
    restaurantId: 2,
  },
  {
    id: 3,
    image: bhujiya3,
    images: [bhujiya3, bhujiya4, bhujiya1, bhujiya2],
    title: "Pudina Bhujiya",
    portion: "200 Gram",
    desc: "Pudina Bhujiya is infused with refreshing mint (pudina) flavor blended into crispy potato strands. Each bite delivers a perfect balance of crunch and aromatic freshness, ideal for tea-time or casual snacking.",
    rating: "4.8",
    reviews: "6.2k",
    orders: "980",
    status: "Open - Close at 10:30pm",
    slots: ["10:30-11:30", "12:30-1:30", "2:30-3:30"],
    isOpen: true,
    view: "2.2k",
    type: "veg",
    price: 119,
    offer: 149,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 4,
    image: bhujiya4,
    images: [bhujiya4, bhujiya1, bhujiya2, bhujiya3],
    title: "Sadi Bhujiya",
    portion: "250 Gram",
    desc: "Sadi Bhujiya features traditional crispy potato strands with a subtle blend of spices. Lightly fried for perfect crunch, this snack is ideal for everyday munching, tea-time, or festive gatherings. Hygienically packed for freshness.",
    rating: "4.7",
    reviews: "5.8k",
    orders: "870",
    status: "Open - Close at 10:30pm",
    slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
    isOpen: true,
    view: "1.9k",
    type: "veg",
    price: 109,
    offer: 139,
    off: 21,
    restaurantId: 2,
  },
  {
    id: 5,
    image: bhujiya5,
    images: [bhujiya5, bhujiya2, bhujiya3, bhujiya1],
    title: "Masala Bhujiya",
    portion: "200 Gram",
    desc: "Masala Bhujiya is a spicy delight made from crispy potato strands tossed in a rich blend of Indian masalas. Perfect for those who enjoy bold and tangy flavors with every bite. Ideal for snacking, parties, or gifting.",
    rating: "4.9",
    reviews: "7.0k",
    orders: "1100",
    status: "Open - Close at 11:00pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: "3.0k",
    type: "veg",
    price: 129,
    offer: 159,
    off: 19,
    restaurantId: 2,
  },
  {
    id: 6,
    image: bhujiya6,
    images: [bhujiya6, bhujiya1, bhujiya4, bhujiya3],
    title: "Makka Bhujiya",
    portion: "250 Gram",
    desc: "Makka Bhujiya is prepared using crispy corn strands blended with traditional spices for a crunchy and flavorful snack. Lightly spiced and perfectly fried, this bhujiya is perfect for tea-time, parties, and casual snacking.",
    rating: "4.8",
    reviews: "6.3k",
    orders: "1020",
    status: "Open - Close at 10:30pm",
    slots: ["11:30-12:30", "1:30-2:30", "3:30-4:30"],
    isOpen: true,
    view: "2.4k",
    type: "veg",
    price: 129,
    offer: 159,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 7,
    image: bhujiya7,
    images: [bhujiya7, bhujiya3, bhujiya2, bhujiya5],
    title: "Tomato Bhujiya",
    portion: "200 Gram",
    desc: "Tomato Bhujiya is a tangy, flavorful snack made from crispy potato strands coated with a rich tomato masala. Every bite delivers a crunchy texture and zesty taste, perfect for tea-time, festive occasions, or casual munching.",
    rating: "4.9",
    reviews: "7.1k",
    orders: "1080",
    status: "Open - Close at 11:00pm",
    slots: ["10:30-11:30", "12:30-1:30", "2:30-3:30"],
    isOpen: true,
    view: "2.8k",
    type: "veg",
    price: 119,
    offer: 149,
    off: 20,
    restaurantId: 2,
  },
    {
    id: 8,
    image: bhujiya1,
    images: [bhujiya1, bhujiya4, bhujiya2, bhujiya3],
    title: "Cheese Bhujiya",
    portion: "250 Gram",
    desc: "Cheese Bhujiya combines crispy potato strands with a rich cheesy coating for a deliciously savory snack. Perfect for kids, parties, or evening munching. Crispy, flavorful, and packed fresh for maximum crunch.",
    rating: "4.8",
    reviews: "6.5k",
    orders: "980",
    status: "Open - Close at 10:30pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: "2.2k",
    type: "veg",
    price: 139,
    offer: 169,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 9,
    image: bhujiya2,
    images: [bhujiya2, bhujiya5, bhujiya3, bhujiya1],
    title: "Garlic Bhujiya",
    portion: "200 Gram",
    desc: "Garlic Bhujiya is a crispy, savory snack infused with aromatic garlic flavor. Lightly spiced and perfectly fried, it’s ideal for tea-time, festive occasions, or a crunchy on-the-go snack. Hygienically packed to retain freshness.",
    rating: "4.9",
    reviews: "7.0k",
    orders: "1100",
    status: "Open - Close at 11:00pm",
    slots: ["11:00-12:00", "1:00-2:00", "3:00-4:00"],
    isOpen: true,
    view: "2.7k",
    type: "veg",
    price: 129,
    offer: 159,
    off: 19,
    restaurantId: 2,
  },
  {
    id: 10,
    image: bhujiya3,
    images: [bhujiya3, bhujiya6, bhujiya1, bhujiya4],
    title: "Spicy Chili Bhujiya",
    portion: "250 Gram",
    desc: "Spicy Chili Bhujiya is a hot and crunchy snack made from perfectly fried potato strands tossed in fiery Indian spices. Each bite delivers a punch of flavor, making it ideal for spice lovers and party snacking.",
    rating: "5.0",
    reviews: "7.5k",
    orders: "1200",
    status: "Open - Close at 11:00pm",
    slots: ["10:30-11:30", "12:30-1:30", "2:30-3:30"],
    isOpen: true,
    view: "3.0k",
    type: "veg",
    price: 149,
    offer: 179,
    off: 17,
    restaurantId: 2,
  },

];

export default ShyamBhujiyaData;
