import item1 from "../../assets/chana1.jpg";
import item2 from "../../assets/chana1.jpg";
import item3 from "../../assets/chana1.jpg";
import item4 from "../../assets/chana1.jpg";
import item5 from "../../assets/chana1.jpg";

const SingleItemsList = [
  {
    id: 1,
    image: item1,
    images: [item1, item2, item3, item4],
    title: "Palak Chana Dal",
    portion: "250 Gram",
    desc: "Palak Chana Dal is a crunchy and flavorful snack made from premium split chana dal coated with a light spinach seasoning. Carefully fried to golden perfection, it delivers a crisp texture combined with a mild earthy flavor. The balanced spices and freshness of palak essence make it a healthy yet tasty choice for daily snacking, tea-time moments, and festive gatherings.",
    rating: "4.8",
    reviews: "6.5k",
    orders: "950",
    status: "Open - Close at 10:30pm",
    slots: ["10:00-11:00", "12:00-1:00", "2:00-3:00"],
    isOpen: true,
    view: "2.4k",
    type: "veg",
    price: 149,
    offer: 179,
    off: 17,
    restaurantId: 2,
  },
  {
    id: 2,
    image: item2,
    images: [item2, item3, item4, item1],
    title: "Moong Dal Masala",
    portion: "250 Gram",
    desc: "Moong Dal Masala is prepared using crispy fried moong lentils blended with bold Indian spices. Each bite offers a satisfying crunch and a mildly spicy kick that enhances its natural flavor. Perfect for everyday snacking, festive platters, and serving guests, it is hygienically packed to maintain freshness and crispiness.",
    rating: "4.9",
    reviews: "7.2k",
    orders: "1100",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "3.0k",
    type: "veg",
    price: 159,
    offer: 199,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 3,
    image: item3,
    images: [item3, item4, item2, item1],
    title: "Heeng Chana",
    portion: "250 Gram",
    desc: "Heeng Chana is a traditional crispy snack infused with the bold aroma of pure asafoetida (heeng). Made from roasted chana coated with special spices, it delivers a rich, tangy, and slightly spicy flavor. Ideal for those who enjoy authentic Indian tastes, it pairs perfectly with tea and festive occasions.",
    rating: "4.7",
    reviews: "5.8k",
    orders: "870",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "2.1k",
    type: "veg",
    price: 139,
    offer: 169,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 4,
    image: item4,
    images: [item4, item2, item3, item1],
    title: "Bombay Chana",
    portion: "500 Gram",
    desc: "Bombay Chana is a spicy and crunchy snack inspired by Mumbai street-style flavors. Premium roasted chana is coated with bold masala seasoning to create a perfect balance of spice and crunch. It is an ideal snack for travel, parties, and everyday munching.",
    rating: "4.8",
    reviews: "6.9k",
    orders: "980",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "2.7k",
    type: "veg",
    price: 199,
    offer: 239,
    off: 16,
    restaurantId: 2,
  },
  {
    id: 5,
    image: item5,
    images: [item5, item2, item3, item4],
    title: "Nattiyam",
    portion: "250 Gram",
    desc: "Nattiyam is a crunchy and flavorful traditional namkeen prepared using premium ingredients and authentic spices. Its unique blend of textures and balanced seasoning delivers a rich taste experience. Perfect for festive occasions, tea-time snacks, and daily munching.",
    rating: "4.6",
    reviews: "4.9k",
    orders: "760",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.9k",
    type: "veg",
    price: 149,
    offer: 179,
    off: 17,
    restaurantId: 2,
  },
  {
    id: 6,
    image: item1,
    images: [item1, item3, item4, item2],
    title: "Tasty Mix",
    portion: "500 Gram",
    desc: "Tasty Mix is a delightful combination of crispy sev, roasted pulses, peanuts, and traditional spices. The perfectly balanced sweet, salty, and spicy flavors make it a favorite among all age groups. Freshly packed to retain its crunch and aroma.",
    rating: "4.8",
    reviews: "6.3k",
    orders: "940",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "2.5k",
    type: "veg",
    price: 219,
    offer: 259,
    off: 15,
    restaurantId: 2,
  },
  {
    id: 7,
    image: item2,
    images: [item2, item4, item3, item1],
    title: "Hara Matar",
    portion: "250 Gram",
    desc: "Hara Matar is a crunchy snack made from premium green peas fried to perfection. Lightly seasoned with aromatic spices, it offers a mildly spicy and satisfying crunch. A healthy and protein-rich snack option for daily enjoyment.",
    rating: "4.7",
    reviews: "5.4k",
    orders: "820",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "2.0k",
    type: "veg",
    price: 159,
    offer: 199,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 8,
    image: item3,
    images: [item3, item1, item2, item4],
    title: "Moong Dal Namkeen",
    portion: "250 Gram",
    desc: "Moong Dal Namkeen is a crispy and lightly salted snack made from carefully selected moong lentils. Its simple yet flavorful taste makes it ideal for tea-time and everyday munching. Hygienically prepared to ensure freshness and crunch.",
    rating: "4.9",
    reviews: "7.0k",
    orders: "1150",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "3.3k",
    type: "veg",
    price: 169,
    offer: 209,
    off: 19,
    restaurantId: 2,
  },
  {
    id: 9,
    image: item4,
    images: [item4, item2, item1, item3],
    title: "Chana Dal Sadi",
    portion: "250 Gram",
    desc: "Chana Dal Sadi is a simple yet delicious crispy snack prepared from premium split chana dal. Lightly salted and fried to golden perfection, it delivers natural flavor and crunch in every bite.",
    rating: "4.6",
    reviews: "4.7k",
    orders: "780",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "1.8k",
    type: "veg",
    price: 139,
    offer: 169,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 10,
    image: item5,
    images: [item5, item3, item2, item1],
    title: "Chana Dal Masala",
    portion: "250 Gram",
    desc: "Chana Dal Masala is a crispy and spicy snack coated with a rich blend of traditional Indian masalas. Its bold flavor and crunchy texture make it perfect for parties and festive platters.",
    rating: "4.8",
    reviews: "6.8k",
    orders: "990",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "2.9k",
    type: "veg",
    price: 159,
    offer: 199,
    off: 20,
    restaurantId: 2,
  },
  {
    id: 11,
    image: item1,
    images: [item1, item2, item3, item4],
    title: "Chatpata Mix",
    portion: "500 Gram",
    desc: "Chatpata Mix is a flavorful blend of crispy ingredients coated with tangy and spicy seasoning. It delivers a perfect balance of sweet, sour, and spicy flavors in every bite, making it a crowd favorite.",
    rating: "4.9",
    reviews: "8.0k",
    orders: "1300",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "3.7k",
    type: "veg",
    price: 229,
    offer: 279,
    off: 18,
    restaurantId: 2,
  },
  {
    id: 12,
    image: item2,
    images: [item2, item3, item4, item1],
    title: "Khatta Meetha",
    portion: "500 Gram",
    desc: "Khatta Meetha is a delicious sweet and sour namkeen mixture made with sev, peanuts, and crunchy pulses. Its unique taste profile makes it perfect for festive celebrations and tea-time snacks.",
    rating: "4.8",
    reviews: "7.4k",
    orders: "1200",
    status: "Open - Close at 11:00pm",
    slots: "",
    isOpen: true,
    view: "3.2k",
    type: "veg",
    price: 249,
    offer: 299,
    off: 17,
    restaurantId: 2,
  },
  {
    id: 13,
    image: item3,
    images: [item3, item4, item2, item1],
    title: "Salted Peanuts",
    portion: "500 Gram",
    desc: "Salted Peanuts are made from premium quality peanuts roasted to perfection and lightly seasoned with fine salt. Crunchy, protein-rich, and satisfying, they are ideal for daily snacking, gatherings, and travel.",
    rating: "4.7",
    reviews: "5.6k",
    orders: "890",
    status: "Open - Close at 10:30pm",
    slots: "",
    isOpen: true,
    view: "2.3k",
    type: "veg",
    price: 199,
    offer: 239,
    off: 16,
    restaurantId: 2,
  },
  {
  id: 14,
  image: item4,
  images: [item4, item1, item2, item3],
  title: "Masala Peanuts",
  portion: "500 Gram",
  desc: "Masala Peanuts are crunchy roasted peanuts coated with a flavorful blend of traditional Indian spices. Each bite delivers a bold, spicy, and slightly tangy taste that makes it perfect for tea-time snacking, parties, and festive gatherings. Carefully prepared and hygienically packed to maintain freshness and crispiness.",
  rating: "4.8",
  reviews: "6.1k",
  orders: "920",
  status: "Open - Close at 11:00pm",
  slots: "",
  isOpen: true,
  view: "2.6k",
  type: "veg",
  price: 219,
  offer: 259,
  off: 15,
  restaurantId: 2,
},
{
  id: 15,
  image: item5,
  images: [item5, item2, item3, item1],
  title: "Special Dry Fruit Mix",
  portion: "500 Gram",
  desc: "Special Dry Fruit Mix is a premium blend of crunchy nuts, roasted pulses, and flavorful spices crafted for a rich snacking experience. Packed with taste and nutrition, it offers a perfect balance of crispiness and aromatic seasoning. Ideal for celebrations, gifting, and healthy daily snacking.",
  rating: "4.9",
  reviews: "8.3k",
  orders: "1400",
  status: "Open - Close at 11:30pm",
  slots: "",
  isOpen: true,
  view: "3.9k",
  type: "veg",
  price: 349,
  offer: 399,
  off: 12,
  restaurantId: 2,
}

];

export default SingleItemsList;
